FROM ruby:3.2.2
WORKDIR /app

# 必要なパッケージをインストール
RUN apt-get update -qq && \
    apt-get install -y build-essential default-mysql-client vim openssl ca-certificates

COPY Gemfile /app/Gemfile
COPY Gemfile.lock /app/Gemfile.lock

# Bundler と Gem の依存関係をインストール
RUN gem install bundler
RUN bundle install

# アプリケーションのソースコードをコピー
COPY . /app

# entrypoint.sh スクリプトをコピーして実行可能にする
COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]